version: "3.9"

services:
  php:
    container_name: szakddoga-php
    hostname: szakdoga-php
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: base
    volumes:
      - .:/var/www
      - ./docker/php.dev.ini:/usr/local/etc/php/php.ini

  web:
    container_name: szakddoga-web
    image: nginx:alpine
    ports:
      - 8800:80
    volumes:
      - .:/var/www
      - ./docker/nginx-localhost.conf:/etc/nginx/conf.d/default.conf

  db:
    container_name: szakdoga-db
    hostname: szakdoga-db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: szakdoga
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3308:3306
    volumes:
      - ./volumes/mysql:/var/lib/mysql